# Generated by Django 3.2.2 on 2021-10-14 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20211014_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Emails', 'verbose_name_plural': 'A lot of Emails'},
        ),
    ]
